### ISSUE TITLE
Error running talk.py example

### ISSUE THREAD

**Issue by StarsoftAnalysis** [abadger/pubmarine#2]
I couldn't get the talk.py example to run because it gave a 'file not found' error on the socket (`/var/tmp/talk.sock`).  I fixed it by changing line 143 from 
`        except ConnectionRefusedError:`
to
`        except (FileNotFoundError, ConnectionRefusedError):`

**Comment by abadger** [comment]
Thanks!  I've pushed a commit with the example catching both errors now.
